version: '3'
services:
  db:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:10.5
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    command: bundle exec hanami server --host=0.0.0.0
    depends_on:
      - db
    ports:
      - '2300:2300'
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - bundle_cache:/usr/local/bundle
volumes:
  bundle_cache:
  postgres_data:
